name: Psalm

on:
  push:
    branches: [master]
  pull_request:

jobs:
  psalm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run Psalm
        run: vendor/bin/psalm --no-progress
